### PR TITLE
BEG-151: Fix Typo

### PR DESCRIPTION
**Pull request by mausham-shrestha-aligent**
Fix Typo

### CODE REVIEW

**Comment by mausham-shrestha-aligent** [comment]
Hi @aligent-lturner , could you please approve this PR? FYI - This fix is already merged in the parent repo. cc @anton-karunarathne-aligent

**Review by anton-karunarathne-aligent — COMMENTED** [review]
This fix is already merge with https://github.com/aligent/magento2-prerender/pull/16/files PR . 
CC: @aligent-lturner

**Comment by mausham-shrestha-aligent** [comment]
Thanks @anton-karunarathne-aligent , I had created this PR a while ago but got off my radar and I was on leave last week. So, I missed that PR you had created. I will decline this PR now.

**Comment by mausham-shrestha-aligent** [comment]
Not sure why it still show the change in the changed file :thinking:

**Pull request closed without merging**
